# All values in this document are the ENVIRONMENT variable names that can override the defaults
# from `default.yaml`
---
executor:
    plugin: EXECUTOR_PLUGIN
    # The NPM module object(s) for the executor plugin(s)
    k8s:
      options:
        kubernetes:
            # The host or IP of the kubernetes cluster
            host: K8S_HOST
            # The jwt token used for authenticating kubernetes requests
            token: K8S_TOKEN
            jobsNamespace: K8S_JOBS_NAMESPACE
        # Launcher container tag to use
        launchVersion: LAUNCH_VERSION
        # Prefix to the pod
        prefix: EXECUTOR_PREFIX
    k8s-vm:
      options:
        # Configuration of Docker
        kubernetes:
            # The host or IP of the kubernetes cluster
            host: K8S_HOST
            # The jwt token used for authenticating kubernetes requests
            token: K8S_TOKEN
            jobsNamespace: K8S_JOBS_NAMESPACE
            baseImage: K8S_BASE_IMAGE
        # Launcher container tag to use
        launchVersion: LAUNCH_VERSION
        # Prefix to the container
        prefix: EXECUTOR_PREFIX
    jenkins:
      options:
        jenkins:
            host: EXECUTOR_JENKINS_HOST
            port: EXECUTOR_JENKINS_PORT
            username: EXECUTOR_JENKINS_USERNAME
            # Jenkins password/token used for authenticating jenkins requests
            password: EXECUTOR_JENKINS_PASSWORD
            # Node labels of Jenkins slaves
            nodeLabel: EXECUTOR_JENKINS_NODE_LABEL
        docker:
            # The path to the docker-compose command
            composeCommand: EXECUTOR_JENKINS_DOCKER_COMPOSE_COMMAND
            # Prefix to the container
            prefix: EXECUTOR_JENKINS_DOCKER_PREFIX
            # Launcher container tag to use
            launchVersion: EXECUTOR_JENKINS_LAUNCH_VERSION
            # Memory limit (docker run `--memory` option)
            memory: EXECUTOR_JENKINS_DOCKER_MEMORY
            # Memory limit include swap (docker run `--memory-swap` option)
            memoryLimit: EXECUTOR_JENKINS_DOCKER_MEMORY_LIMIT
        # The command to start build
        buildScript: EXECUTOR_JENKINS_BUILD_SCRIPT
        # The command to clean up build system
        cleanupScript: EXECUTOR_JENKINS_CLEANUP_SCRIPT
        # Time (seconds) to destroy the job
        cleanupTimeLimit: EXECUTOR_JENKINS_CLEANUP_TIME_LIMIT
        # Interval to detect the stopped job (seconds)
        cleanupWatchInterval: EXECUTOR_JENKINS_CLEANUP_WATCH_INTERVAL
        prefix: EXECUTOR_PREFIX

ecosystem:
    # URL for the User Interface
    api: ECOSYSTEM_API
    # Externally routable URL for the Artifact Store
    store: ECOSYSTEM_STORE

redis:
    # Host of redis cluster
    host: REDIS_HOST
    # Password to connect to redis cluster
    password: REDIS_PASSWORD
    # Host of redis cluster
    port: REDIS_PORT
    # Prefix for the queue name
    prefix: REDIS_QUEUE_PREFIX
